### ISSUE TITLE
Lockscreen Progress incorrect in RepeatMode.track

### ISSUE THREAD

**Issue by jspizziri** [doublesymmetry/SwiftAudioEx#15]
**Describe the bug**
When the player is in RepeatMode.track after a few repeats the progress gets stuck at 100%. For more information see [the issue filed with the RNTP library](https://github.com/doublesymmetry/react-native-track-player/issues/1426).

**To Reproduce**

1. Configure playback of a track with RepeatMode.track
2. Play the item.
3. Lock the screen.
4. Wait until the track has repeated a few times
5. Observe the progress is stuck at 100%.

**Expected behavior**

It's expected that the progress would track appropriately after N repeats.

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - OS: iOS
 - Version  15.4.1

**Additional context**

Additionally, I found that once the progress gets stuck if you interact with the controls (e.g. press the "pause" button) the progress will update to its correct position. Additionally, I'll add that this was tested against `v0.15.0`.

**Comment by puckey** [comment]
https://github.com/doublesymmetry/SwiftAudioEx/pull/28 should fix this

**Comment by siddharthan64** [comment]
This still happens as of commit 7fb762d.

**Steps to reproduce:**
1. Play an array of `DefaultAudioItem` with `repeatMode` set to `.queue` 
2. Background the app
3. Wait for next track to start
4. Obserne NowPlaying system view

**Expected behavior:**
Track duration and progress updates when the new track starts to play

**Actual behavior:**
![IMG_8298](https://github.com/doublesymmetry/SwiftAudioEx/assets/5011270/3bf1bea2-31be-469a-bbc6-28bb9d7b8ee8)


**Possible cause:**
When `onCurrentItemChanged` loads the next item, duration and playback values are set to nil

```
nowPlayingInfoController.setWithoutUpdate(keyValues: [
   MediaItemProperty.duration(nil),
   NowPlayingInfoProperty.playbackRate(nil),
  NowPlayingInfoProperty.elapsedPlaybackTime(nil)
])
``` 

The following method `func loadNowPlayingMetaValues` only sets albumTitle, artist and title.  

Method `func updateNowPlayingPlaybackValues()` never gets called until state changes in 
` func AVWrapper(didChangeState state: AVPlayerWrapperState)` method
